/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IL2WormholeGateway,
  IL2WormholeGatewayInterface,
} from "../IL2WormholeGateway";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes",
        name: "vaa",
        type: "bytes",
      },
    ],
    name: "receiveTbtc",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IL2WormholeGateway__factory {
  static readonly abi = _abi;
  static createInterface(): IL2WormholeGatewayInterface {
    return new utils.Interface(_abi) as IL2WormholeGatewayInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IL2WormholeGateway {
    return new Contract(address, _abi, signerOrProvider) as IL2WormholeGateway;
  }
}
