/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { IWormhole, IWormholeInterface } from "../IWormhole";

const _abi = [
  {
    inputs: [],
    name: "chainId",
    outputs: [
      {
        internalType: "uint16",
        name: "",
        type: "uint16",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "messageFee",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IWormhole__factory {
  static readonly abi = _abi;
  static createInterface(): IWormholeInterface {
    return new utils.Interface(_abi) as IWormholeInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IWormhole {
    return new Contract(address, _abi, signerOrProvider) as IWormhole;
  }
}
