/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IWormholeRelayer,
  IWormholeRelayerInterface,
} from "../IWormholeRelayer";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint16",
        name: "targetChain",
        type: "uint16",
      },
      {
        internalType: "uint256",
        name: "receiverValue",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "gasLimit",
        type: "uint256",
      },
    ],
    name: "quoteEVMDeliveryPrice",
    outputs: [
      {
        internalType: "uint256",
        name: "nativePriceQuote",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "targetChainRefundPerGasUnused",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint16",
        name: "targetChain",
        type: "uint16",
      },
      {
        internalType: "address",
        name: "targetAddress",
        type: "address",
      },
      {
        internalType: "bytes",
        name: "payload",
        type: "bytes",
      },
      {
        internalType: "uint256",
        name: "receiverValue",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "gasLimit",
        type: "uint256",
      },
      {
        components: [
          {
            internalType: "uint16",
            name: "chainId",
            type: "uint16",
          },
          {
            internalType: "bytes32",
            name: "emitterAddress",
            type: "bytes32",
          },
          {
            internalType: "uint64",
            name: "sequence",
            type: "uint64",
          },
        ],
        internalType: "struct WormholeTypes.VaaKey[]",
        name: "vaaKeys",
        type: "tuple[]",
      },
      {
        internalType: "uint16",
        name: "refundChain",
        type: "uint16",
      },
      {
        internalType: "address",
        name: "refundAddress",
        type: "address",
      },
    ],
    name: "sendVaasToEvm",
    outputs: [
      {
        internalType: "uint64",
        name: "sequence",
        type: "uint64",
      },
    ],
    stateMutability: "payable",
    type: "function",
  },
];

export class IWormholeRelayer__factory {
  static readonly abi = _abi;
  static createInterface(): IWormholeRelayerInterface {
    return new utils.Interface(_abi) as IWormholeRelayerInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IWormholeRelayer {
    return new Contract(address, _abi, signerOrProvider) as IWormholeRelayer;
  }
}
