/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { Reimbursable, ReimbursableInterface } from "../Reimbursable";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "newReimbursementPool",
        type: "address",
      },
    ],
    name: "ReimbursementPoolUpdated",
    type: "event",
  },
  {
    inputs: [],
    name: "reimbursementPool",
    outputs: [
      {
        internalType: "contract ReimbursementPool",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "contract ReimbursementPool",
        name: "_reimbursementPool",
        type: "address",
      },
    ],
    name: "updateReimbursementPool",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class Reimbursable__factory {
  static readonly abi = _abi;
  static createInterface(): ReimbursableInterface {
    return new utils.Interface(_abi) as ReimbursableInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): Reimbursable {
    return new Contract(address, _abi, signerOrProvider) as Reimbursable;
  }
}
