/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface AbstractTBTCDepositorInterface extends utils.Interface {
  functions: {
    "SATOSHI_MULTIPLIER()": FunctionFragment;
    "bridge()": FunctionFragment;
    "tbtcVault()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "SATOSHI_MULTIPLIER",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "bridge", values?: undefined): string;
  encodeFunctionData(functionFragment: "tbtcVault", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "SATOSHI_MULTIPLIER",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "bridge", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "tbtcVault", data: BytesLike): Result;

  events: {};
}

export interface AbstractTBTCDepositor extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: AbstractTBTCDepositorInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    SATOSHI_MULTIPLIER(overrides?: CallOverrides): Promise<[BigNumber]>;

    bridge(overrides?: CallOverrides): Promise<[string]>;

    tbtcVault(overrides?: CallOverrides): Promise<[string]>;
  };

  SATOSHI_MULTIPLIER(overrides?: CallOverrides): Promise<BigNumber>;

  bridge(overrides?: CallOverrides): Promise<string>;

  tbtcVault(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    SATOSHI_MULTIPLIER(overrides?: CallOverrides): Promise<BigNumber>;

    bridge(overrides?: CallOverrides): Promise<string>;

    tbtcVault(overrides?: CallOverrides): Promise<string>;
  };

  filters: {};

  estimateGas: {
    SATOSHI_MULTIPLIER(overrides?: CallOverrides): Promise<BigNumber>;

    bridge(overrides?: CallOverrides): Promise<BigNumber>;

    tbtcVault(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    SATOSHI_MULTIPLIER(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    bridge(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    tbtcVault(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
