/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface ITBTCVaultInterface extends utils.Interface {
  functions: {
    "optimisticMintingFeeDivisor()": FunctionFragment;
    "optimisticMintingRequests(uint256)": FunctionFragment;
    "tbtcToken()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "optimisticMintingFeeDivisor",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "optimisticMintingRequests",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "tbtcToken", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "optimisticMintingFeeDivisor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "optimisticMintingRequests",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "tbtcToken", data: BytesLike): Result;

  events: {};
}

export interface ITBTCVault extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: ITBTCVaultInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    optimisticMintingFeeDivisor(overrides?: CallOverrides): Promise<[number]>;

    optimisticMintingRequests(
      depositKey: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    tbtcToken(overrides?: CallOverrides): Promise<[string]>;
  };

  optimisticMintingFeeDivisor(overrides?: CallOverrides): Promise<number>;

  optimisticMintingRequests(
    depositKey: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  tbtcToken(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    optimisticMintingFeeDivisor(overrides?: CallOverrides): Promise<number>;

    optimisticMintingRequests(
      depositKey: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber] & {
        requestedAt: BigNumber;
        finalizedAt: BigNumber;
      }
    >;

    tbtcToken(overrides?: CallOverrides): Promise<string>;
  };

  filters: {};

  estimateGas: {
    optimisticMintingFeeDivisor(overrides?: CallOverrides): Promise<BigNumber>;

    optimisticMintingRequests(
      depositKey: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    tbtcToken(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    optimisticMintingFeeDivisor(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    optimisticMintingRequests(
      depositKey: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    tbtcToken(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
