/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result, EventFragment } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface ReimbursableInterface extends utils.Interface {
  functions: {
    "reimbursementPool()": FunctionFragment;
    "updateReimbursementPool(address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "reimbursementPool",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "updateReimbursementPool",
    values: [string]
  ): string;

  decodeFunctionResult(
    functionFragment: "reimbursementPool",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateReimbursementPool",
    data: BytesLike
  ): Result;

  events: {
    "ReimbursementPoolUpdated(address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "ReimbursementPoolUpdated"): EventFragment;
}

export type ReimbursementPoolUpdatedEvent = TypedEvent<
  [string],
  { newReimbursementPool: string }
>;

export type ReimbursementPoolUpdatedEventFilter =
  TypedEventFilter<ReimbursementPoolUpdatedEvent>;

export interface Reimbursable extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: ReimbursableInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    reimbursementPool(overrides?: CallOverrides): Promise<[string]>;

    updateReimbursementPool(
      _reimbursementPool: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  reimbursementPool(overrides?: CallOverrides): Promise<string>;

  updateReimbursementPool(
    _reimbursementPool: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    reimbursementPool(overrides?: CallOverrides): Promise<string>;

    updateReimbursementPool(
      _reimbursementPool: string,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "ReimbursementPoolUpdated(address)"(
      newReimbursementPool?: null
    ): ReimbursementPoolUpdatedEventFilter;
    ReimbursementPoolUpdated(
      newReimbursementPool?: null
    ): ReimbursementPoolUpdatedEventFilter;
  };

  estimateGas: {
    reimbursementPool(overrides?: CallOverrides): Promise<BigNumber>;

    updateReimbursementPool(
      _reimbursementPool: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    reimbursementPool(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    updateReimbursementPool(
      _reimbursementPool: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
